### ISSUE TITLE
"Failed to write response to socket" thrown on client disconnect

### ISSUE THREAD

**Issue by qixils** [qixils/java-crowd-control#47]
Minor issue
```
[00:42:33 WARN] [CC-Response]: Failed to write response to socket
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_312]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_312]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:134) ~[?:1.8.0_312]
        at dev.qixils.crowdcontrol.socket.Response.send(Response.java:466) ~[Response.class:?]
        at dev.qixils.crowdcontrol.socket.SocketThread.shutdown(SocketThread.java:93) ~[SocketThread.class:?]
        at dev.qixils.crowdcontrol.socket.SocketManager.shutdown(SocketManager.java:39) ~[SocketManager.class:?]
        at dev.qixils.crowdcontrol.socket.EffectExecutor.run(EffectExecutor.java:59) ~[EffectExecutor.class:?]
        at dev.qixils.crowdcontrol.socket.SocketThread.run(SocketThread.java:55) ~[SocketThread.class:?]
```

**Comment by qixils** [comment]
Still occurring
```
[01:25:23 INFO] [CC-SocketThread]: Client disconnected from server (5B1C33)
>
[01:25:25 INFO]: Stopping server
[01:25:25 WARN] [CC-Core]: Encountered an exception while shutting down socket
java.net.SocketException: Connection reset by peer: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_312]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_312]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143) ~[?:1.8.0_312]
        at dev.qixils.crowdcontrol.socket.Response.rawSend(Response.java:472) ~[Response.class:?]
        at dev.qixils.crowdcontrol.socket.SocketThread.shutdown(SocketThread.java:97) ~[SocketThread.class:?]
        at dev.qixils.crowdcontrol.socket.ServerSocketManager.shutdown(ServerSocketManager.java:84) ~[ServerSocketManager.class:?]
        at dev.qixils.crowdcontrol.CrowdControl.shutdown(CrowdControl.java:425) ~[CrowdControl.class:?]
```
